import { createConfig } from '@gluestack-style/react';

export const config = createConfig({
  aliases: {
    bg: 'backgroundColor',
    bgColor: 'backgroundColor',
    rounded: 'borderRadius',
    h: 'height',
    w: 'width',
    p: 'padding',
    px: 'paddingHorizontal',
    py: 'paddingVertical',
    m: 'margin',
    mx: 'marginHorizontal',
    my: 'marginVertical',
  },
  tokens: {
    colors: {
      primary: '#4CAF50',
      primaryDark: '#388E3C',
      primaryLight: '#81C784',
      secondary: '#FF9800',
      secondaryDark: '#F57C00',
      secondaryLight: '#FFB74D',
      error: '#F44336',
      errorDark: '#D32F2F',
      errorLight: '#E57373',
      warning: '#FFC107',
      info: '#2196F3',
      success: '#4CAF50',
      background: '#FFFFFF',
      surface: '#F5F5F5',
      text: '#212121',
      textSecondary: '#757575',
      textDisabled: '#BDBDBD',
      border: '#E0E0E0',
      white: '#FFFFFF',
      black: '#000000',
    },
    space: {
      xs: 4,
      sm: 8,
      md: 16,
      lg: 24,
      xl: 32,
      xxl: 48,
    },
    borderRadius: {
      sm: 4,
      md: 8,
      lg: 12,
      xl: 16,
      full: 9999,
    },
    fontSizes: {
      xs: 12,
      sm: 14,
      md: 16,
      lg: 18,
      xl: 20,
      xxl: 24,
      xxxl: 32,
    },
  },
});
